### ISSUE TITLE
Pasting on iOS

### ISSUE THREAD

**Issue by hope-portal-services** [AlbertSabate/react-pin-code-input#3]
When pasting from a mobile iOS device, the last digit of the array is ignored, filling in, for example, 5 fields instead of 6. This does not happen on Android and does not happen on desktop. There doesn't seem to be a way to override the onPaste handler through a custom prop to solve this manually.

**Comment by AlbertSabate** [comment]
Hi hope-portal-service, let me take a look to this. May I know the iOS version?

**Comment by hope-portal-services** [comment]
Hi @AlbertSabate, I'm seeing this on a handful of devices with different iOS versions:

iPhone 11 Pro Max - v14.0.1
iPhone 12 - v14.4.2

Confirmed this does not occur on iPad Mini 2 v12.5.2
Confirmed this is not happening on Android devices

**What I'm seeing:**
X digit string is pasted into the fields, only X - 1 characters are pasted, leaving the final field blank

**Comment by AlbertSabate** [comment]
Got it! Thanks for the extra info. I will try to reproduce on my end, and push a fix for this.

**Comment by AlbertSabate** [comment]
Found and fixed the issue, however I need to test it more and fix the pipelines before publish the release. (Hope have time to finish it by next week)

FYI react peerDependencies will be bump to v17. The package is compatible from v16.6 as well but peerDeps will complain.

**Comment by hope-portal-services** [comment]
Thanks @AlbertSabate, look forward to getting this solved.

**Comment by AlbertSabate** [comment]
Hi @hope-portal-services,

v2 has been released, this version includes the fix for Pasting on iOS. The component works on the same way of version 1, so you don't need to do any change in your code.

Changelog: https://github.com/AlbertSabate/react-pin-code-input/releases/tag/v2.0.0
